### ISSUE TITLE
FYI, Compatibility issue with Arduino Editor

### ISSUE THREAD

**Issue by LtInPB** [budryerson/TFMini-Plus-I2C#9]
Thanks for your effort on the TFMini Plus.

I use Arduino's online Editor, instead of the IDE.  (recently shifted from Window to a ChromeBox). 
FYI, I plan on using your code with  a Elegoo Mega 2560.

However, during the import of the Zip file with the Editor, the editor display this message.  Is this fatal? 

![image](https://user-images.githubusercontent.com/68661633/103030215-2eafd280-4510-11eb-9203-240dadbf0771.png)

**Comment by budryerson** [comment]
Dear LtInPB,
I'm sorry I missed this.  Holidays and such, y'know?
Sadly, I am not familiar with Arduino's on-line IDE.  I do have a Mega2560, so I can give it a try.
Will you please send me an archive of the sketch you are trying to run and a text file of the results you are getting.  Please include pictures, if you can.  They are surprisingly helpful.
Again, I apologize for taking so long to respond.  You've probably got everything worked out by now anyway.
Bud Ryerson
San Francisco
